# Servidor Eureka
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url: /infoComposer
    health-check-url-path: /healthComposer
    metadata-map:
      app-owner: cramirez
      description: API generada para el curso de arquitectura de microservicios
      management.port: 6666

# HTTP Server
server:
  port: 6666