# HTTP Server
server:
  port: 5555

# Discovery Server Eureka
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# Server Hystrix
hystrix:
  dashboard:    proxy-stream-allow-list: '*'

# Turbine
turbine:
  aggregator:
    clusterConfig: API.PACIENTE
  appConfig: api.paciente