# HTTP Server
server:
  port: 8761

# Eureka Server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.12:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    hostname: servidor-composer
#  server:
#    wait-time-in-ms-when-sync-empty: 0
#    enable-self-preservation: true

#ribbon:
#  eureka:
#    approximateZoneFromHostname: true
#    hostname: LAPTOP-OQDQ45DP