# Servidor Eureka
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url: /infoAgenda
    health-check-url-path: /healthAgenda
    metadata-map:
      app-owner: cramirez
      description: API generada para el curso de arquitectura de microservicios
      management.port: 4444

# HTTP Server
server:
  port: 4444

# Spring Boot
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: apiagenda
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/api-curso-arquitectura-microservicios
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    continue-on-error: true
  rabbitmq:
    virtual-host: kqmrapfy
    username: kqmrapfy
    password: kvtV3yHLjFFx6qPOgTX7VSNKj-PVa5xh
    addresses: amqps://kqmrapfy:kvtV3yHLjFFx6qPOgTX7VSNKj-PVa5xh@grouse.rmq.cloudamqp.com/kqmrapfy